services:
  app:
    build:
      context: .
    volumes:
      - static:/static
    env_file:
      - .env
    ports:
      - "8000:8000"

  nginx:
    build: ./nginx
    image: nginx:latest
    volumes:
      - static:/static
    ports:
      - "80:80"
    depends_on:
      - app

volumes:
  static:
